version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    container_name: backend-container
    entrypoint: ["npm", "run", "start"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    container_name: frontend-container
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - VITE_BACKEND_URL=http://backend:5000  # frontend will connect to backend container

  # cypress:
  #   build:
  #     context: .
  #     dockerfile: cypress/Dockerfile.cypress
  #   depends_on:
  #     frontend:
  #       condition: service_started
  #   environment:
  #     - CYPRESS_baseUrl=http://frontend:4173
  #   container_name: cypress-container